# Generated by Django 4.2.10 on 2024-04-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_Ratio', '-vote_total', 'title']},
        ),
    ]
